name: Tag TEst

on:
  push:
    tags: 
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v1
    - name: github.ref 
      run: echo ${{ github.ref }}
    - run: ewfwf
