name: Tag TEst

on:
  push:
    tags: 
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v1
    - name: github.ref 
      run: echo ${{ github.ref }}
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - run: echo "${{ steps.get_version.outputs.VERSION }}" 
    - run: ewfwf
