name: tag-push
on: 
  push:
    branches:
    - "master"
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
    - name: Bump version and push tag v1
      uses: anothrNick/github-tag-action@1.7.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
